name: Espresso - Example 10

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '20 1 * * 0'

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - name: Espresso - Example 10
        run: saucectl run --config ./.sauce/runner-ex10.yml
