# Example 4: Run in parallel on hard-coded devices
# Run two tests on separate specific devices in my pool, this can be US/EU
# NOTE: if the devices are busy, these tests will wait until they are free.

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - example4
      - parallelWithStaticAllocation

espresso:
  app: ./apps/my-demo-app-android.apk
  testApp: ./apps/my-demo-app-android-tests.apk

suites:
  - name: "Example 4: Parallel with Static allocation - succesfulLoginTest"
    testOptions:
      class: 
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#succesfulLoginTest
    devices:
      - name: Samsung_Galaxy_S20_real
  - name: "Example 4: Parallel with Static allocation - noUsernameLoginTest"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#noUsernameLoginTest
    devices:
      - name: Samsung_Galaxy_S10_Plus_real

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
