# Example 4: Run in parallel on hard-coded devices
# Run two tests on separate specific devices in my pool, this can be US/EU
# NOTE: if the devices are busy, these tests will wait until they are free.

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - android
      - espresso
      - ex4
    build: Sauce Espresso

espresso:
  app: ./apps/SauceLabs.Mobile.Sample.Espresso.App.apk
  testApp: ./apps/SauceLabs.Mobile.Sample.Espresso.Tests.apk

suites:
  - name: "Sauce Labs Espresso Tests from Example 4 - noPasswordLogin"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#noPasswordLogin"]
    devices:
      - name: Samsung_Galaxy_S20_real
  - name: "Sauce Labs Espresso Tests from Example 4 - noMatchLogin"
    testOptions:
      class: ["com.swaglabsmobileapp.LoginTest#noMatchLogin"]
    devices:
      - name: Samsung_Galaxy_S10_Plus_real

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
