# Example 5: Parallel execution using dynamic devices
# Run two tests on separate specific devices in my pool, this can be US/EU
# Use `deviceNameQuery` to find any free Samsung Galaxy Note
# or Samsung Galaxy S10 and run the test on it.

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - example4
      - parallelWithDynamicAllocation

espresso:
  app: ./apps/my-demo-app-android.apk
  testApp: ./apps/my-demo-app-android-tests.apk

suites:
  - name: "Example 5: Parallel with Dynamic allocation - succesfulLoginTest"
    testOptions:
      class: 
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#succesfulLoginTest
    devices:
      - name: "Samsung Galaxy Note.*"
  - name: "Tests from Example 5: Parallel with Dynamic allocation - noUsernameLoginTest"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#noUsernameLoginTest
    devices:
      - name: "Samsung Galaxy S10.*"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
