# Example 1: minimal configuration.
# Run all tests on any available *single* device in my pool, this can be US/EU

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10

espresso:
  app: ./apps/my-demo-app-android.apk
  testApp: ./apps/my-demo-app-android-tests.apk

suites:
  - name: "Example 1 - All tests"
    devices:
      - name: "Samsung.*"
        options:
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
