# Example 3: Run each test on its own device
# Run two tests on separately available devices in my pool, this can be US/EU

apiVersion: v1alpha
kind: espresso
sauce:
  # This can be `eu-central-1` or  `us-west-1`
  region: eu-central-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    tags:
      - example3
      - oneTestPerDevice

espresso:
  app: ./apps/my-demo-app-android.apk
  testApp: ./apps/my-demo-app-android-tests.apk

suites:
  - name: "Example 3: One test per device - successfulLogin"
    testOptions:
      class: 
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#succesfulLoginTest
    devices:
      - name: "Samsung.*"
        options:
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
  - name: "Example 3: One test per device - noUsernameLogin"
    testOptions:
      class:
        - com.saucelabs.mydemoapp.android.view.activities.LoginTest#noUsernameLoginTest
    devices:
      - name: "Samsung.*"
        options:
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./reports/
